a = input("Enter strings seperated by comma : ")
b = a.split(', ')
b = a.split(',')
print(b)

print("Your input : ")
print(', '.join(b) + '\n')
print("Sorted(alphanumerically) : ")
print(', '.join(sorted(b)) + '\n')
print("Reversed : ")
b.reverse()
print(', '.join(b) + '\n')
print("Sorted alphanumerically and then reversed : ")
print(', '.join(sorted(b,reverse = True)))