sample_list = (1,2,3,'Saurav',5,6,7,'Insight-Workshop',9,10)
print("Sample tuple is :",sample_list)
tuple_to_list = list(sample_list)
print("Sample tuple converted to list is :",tuple_to_list)
print(type(tuple_to_list))